export const FILTER = 'FILTER';
export const CHANGE_HEADER = 'CHANGE_HEADER';
// AUTH ACTIONS
export const SET_AUTH = 'SET_AUTH';
export const SET_ERROR = 'SET_ERROR';
// QUINIELA
export const GET_QUINIELA_STRUCTURES = 'GET_QUINIELA_STRUCTURES';
// GAME options
export const POST_GAME = 'POST_GAME';
export const POST_PREDICTIONS = 'POST_PREDICTIONS';
export const GET_PREDICTIONS = 'GET_PREDICTIONS';
export const GET_QUINIELA_POSITIONS = 'GET_QUINIELA_POSITIONS';
export const GET_GAME = 'GET_GAME';
export const SET_GAME_GRUPOS = 'SET_GAME_GRUPOS';
export const COUNSTRIES_BY_GROUP = 'COUNSTRIES_BY_GROUP';
export const PATCH_UPDATE_GAME = 'PATCH_UPDATE_GAME';
export const SET_GAME_OCTAVOS = 'SET_GAME_OCTAVOS';
export const SET_GAME_CUARTOS = 'SET_GAME_CUARTOS';
export const SET_GAME_SEMIFINALES = 'SET_GAME_SEMIFINALES';
export const SET_GAME_TERCEROS = 'SET_GAME_TERCEROS';
export const SET_GAME_FINAL = 'SET_GAME_FINAL';
